# Generated by Django 3.2.2 on 2021-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fyfuy', upload_to='gllery'),
            preserve_default=False,
        ),
    ]
